name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
      - run: |
          echo "NO_COVERAGE_RUN=$(if [ -z "$(npx nx print-affected --select=projects)" ]; then echo "true"; else echo "false";fi)" >> $GITHUB_ENV
      - run: echo "${{ env.NO_COVERAGE_RUN }}"
      - name: Code Coverage Summary
        uses: dkhunt27/nx-code-coverage@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-folder: ./coverage
          coverage-base-folder: ./coverage-base
          gist-token: ${{ secrets.GIST_SECRET }}
          gist-id: 64d6f926915811aa067f60e6a70735c8
          color: green
          named-logo: jest
          no-coverage-ran: ${{ env.NO_COVERAGE_RUN }}
