name: Package Release

on:
  push:
    tags:
      - '*/*.*.*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - uses: actions/github-script@v6
        id: project
        with:
          result-encoding: string
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '').split('/')[0]
      - uses: actions/github-script@v6
        id: version
        with:
          result-encoding: string
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '').split('/')[1]
      - name: Build
        run: |
          npx nx run ${{ steps.project.outputs.result }}:build

      - name: Publish
        run: |
          node path/to/publish.mjs ${{ steps.project.outputs.result }} --version ${{ steps.version.outputs.result }} --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
